- name: gpt-4.1-2025-04-14
  sku:
    name: GlobalStandard
    capacity: 232
  model:
    format: OpenAI
    name: gpt-4.1
    version: 2025-04-14
  versionUpgradeOption: OnceCurrentVersionExpired

- name: gpt-4.1-mini-2025-04-14
  sku:
    name: GlobalStandard
    capacity: 500
  model:
    format: OpenAI
    name: gpt-4.1-mini
    version: 2025-04-14
  versionUpgradeOption: OnceCurrentVersionExpired

- name: gpt-4.1-nano-2025-04-14
  sku:
    name: GlobalStandard
    capacity: 500
  model:
    format: OpenAI
    name: gpt-4.1-nano
    version: 2025-04-14
  versionUpgradeOption: OnceCurrentVersionExpired

- name: gpt-4o-2024-11-20
  sku:
    name: GlobalStandard
    capacity: 50
  model:
    format: OpenAI
    name: gpt-4o
    version: 2024-11-20
  versionUpgradeOption: OnceCurrentVersionExpired
  
- name: gpt-4o-mini-2024-07-18
  sku:
    name: GlobalStandard
    capacity: 50
  model:
    format: OpenAI
    name: gpt-4o-mini
    version: 2024-07-18
  versionUpgradeOption: OnceCurrentVersionExpired

- name: o3-mini-2025-01-31
  sku:
    name: GlobalStandard
    capacity: 50
  model:
    format: OpenAI
    name: o3-mini
    version: 2025-01-31
  versionUpgradeOption: OnceCurrentVersionExpired

- name: o1-2024-12-17
  sku:
    name: GlobalStandard
    capacity: 50
  model:
    format: OpenAI
    name: o1
    version: 2024-12-17
  versionUpgradeOption: OnceCurrentVersionExpired

- name: o1-mini-2024-09-12
  sku:
    name: GlobalStandard
    capacity: 50
  model:
    format: OpenAI
    name: o1-mini
    version: 2024-09-12
  versionUpgradeOption: OnceNewDefaultVersionAvailable

- name: text-embedding-ada-002
  sku:
    name: GlobalStandard
    capacity: 150
  model:
    format: OpenAI
    name: text-embedding-ada-002
    version: "2"
  versionUpgradeOption: NoAutoUpgrade

- name: text-embedding-3-small
  sku:
    name: GlobalStandard
    capacity: 150
  model:
    format: OpenAI
    name: text-embedding-3-small
    version: "1"
  versionUpgradeOption: NoAutoUpgrade

- name: text-embedding-3-large
  sku:
    name: GlobalStandard
    capacity: 150
  model:
    format: OpenAI
    name: text-embedding-3-large
    version: "1"
  versionUpgradeOption: NoAutoUpgrade

# - name: gpt-image-1-2025-04-15
#   sku:
#     name: GlobalStandard
#     capacity: 2
#   model:
#     format: OpenAI
#     name: gpt-image-1
#     version: 2025-04-15
#   versionUpgradeOption: OnceNewDefaultVersionAvailable
